# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, pull_request]

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: 'Tests'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          install-dependencies: true
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Install dependencies
        run: |
          if [ -e pnpm-lock.yaml ]; then
          pnpm install --frozen-lockfile
          else
          pnpm install
          fi
      - name: Lint
        run: pnpm lint
      - name: Run Tests
        run: pnpm test

  floating:
    name: 'Floating Dependencies'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          install-dependencies: true
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --no-lockfile
      - name: Run Tests
        run: npm run test

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    needs: 'test'

    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-5.0
          - ember-lts-5.4
          - ember-lts-5.8
          - ember-lts-5.12
          - ember-6.0
          - ember-lts-6.4
          - embroider-safe
          - embroider-optimized

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          install-dependencies: true
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Install dependencies
        run: |
          if [ -e pnpm-lock.yaml ]; then
          pnpm install --frozen-lockfile
          else
          pnpm install
          fi
      - name: Run Tests
        run: pnpm --filter test-app test:ember-compatibility ${{ matrix.try-scenario }}
